### ISSUE TITLE
continue attempting to reconcile when secret already exists

### ISSUE THREAD

**Issue by travisghansen** [isindir/sops-secrets-operator#65] opened 2021-04-28 22:04 UTC
Maybe I didn't wait long enough, but when the secret already exists it seemed to stop attempting to manage it. I manually deleted the secret to let it take control/recreate but it seemed to be done messing with it.

Did I just not wait long enough or should the controller be updated to keep trying over time?

**Comment by eplightning** [comment] 2021-04-29 06:16
Could you provide logs? I used this operator on my cluster for few months now and never had any issues with this.

**Comment by isindir** [comment] 2021-04-29 07:27
@travisghansen it feels like #63 introduced the bug, I'll roll it out today if that is the case. I could partially reproduce the issue:
* create kind cluster
* create age key
* apply crd via `make install`
* encrypt SopsSecret example and apply to cluster
* run in shell via `make run`
* it created secrets
* stopped operator
* restarted local copy of operator and removed sops object - should have removed all child secrets, but that did not happen

**Comment by isindir** [comment] 2021-04-29 07:50
@travisghansen and @eplightning - confirmed,  by reverting the change operator behaves as expected. I'll revert the change for now and will work on introducing same binaryData feature.

**Comment by travisghansen** [comment] 2021-04-29 12:52
I think we may be talking about different things...and I’m fairly confident I wasn’t running the version that has the binary data feature anyhow.

In my case it was like this..

- create a secret and use it
- discovered sops operator and install it
- create a sops secret to manage the secret created in step 1
- operator complains secret already exists (this was expected and good)
- manually delete secret created in step 1
- wait for operator to try again to create the secret

I may not have waited long enough but it never seemed to create the secret in that last step.

**Comment by eplightning** [comment] 2021-04-29 13:09
Also isn't removing `Secret` resources owned by removed `SopsSecret` handled by Kubernetes API server (based on ownerReferences)?

**Comment by isindir** [comment] 2021-04-29 13:09
@travisghansen Can you please test with latest version of chart. As I'm pinning version of the docker image via chart - you may have used broken version of operator if it wasn't overriden. For me behaviour was different in both cases. Also operator should be triggered by CRUD on SopsSecret objects and k8s Secrets objects owned by SopsSecret as parent. And once you deleted the secret owned by SopsSecret - reconcile loop should have re-created k8s secret.
As a side: binaryData is more of convenience, as native k8s resource does not have such field: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#secret-v1-core

in `SopsSecret` - `data` field is `stringData` of k8s `Secret`, but there is no notion of `data` field of k8s `Secret`. I guess the best solution would be to map 1:1 `data to data` and `stringData to StringData` between `SopsSecret` and `Secret`, which will be breaking change.

**Comment by isindir** [comment] 2021-04-29 13:12
> Also isn't removing `Secret` resources owned by removed `SopsSecret` handled by Kubernetes API server (based on ownerReferences)?

If one removes owning `SopsSecret` - all owned `Secrets` should be removed by k8s, but re-creation of `Secret` if `SopsSecret` remains is responsibility of operator.

**Comment by isindir** [comment] 2021-04-29 13:16
> I think we may be talking about different things...and I’m fairly confident I wasn’t running the version that has the binary data feature anyhow.
> 
> In my case it was like this..
> 
> * create a secret and use it
> * discovered sops operator and install it
> * create a sops secret to manage the secret created in step 1
> * operator complains secret already exists (this was expected and good)
> * manually delete secret created in step 1
> * wait for operator to try again to create the secret
> 
> I may not have waited long enough but it never seemed to create the secret in that last step.

scenario looks different, but when the slot (secret name) was freed, I'd expect operator to recreate secret, as there is re-scheduling implemented - it is set by default to 5 min ( https://github.com/isindir/sops-secrets-operator/blob/master/controllers/sopssecret_controller.go#L83 ). What I have tested is operator was not taking ownership of already pre-existing objects which it should own after operator was restarted.

**Comment by eplightning** [comment] 2021-04-29 13:37
I think the RequeueAfter is not set on success (https://github.com/isindir/sops-secrets-operator/blob/6f57f2eac972cfb00a0937c360985fc94cb80327/controllers/sopssecret_controller.go#L222) which is probably why the removal of unowned `Secret` wasn't picked up.

Please also note that `stringData` is not a seperately persisted field in `Secret` resource. It's a helper field that is automatically merged into `data` by kube-apiserver:
```
	// stringData allows specifying non-binary secret data in string form.
	// It is provided as a write-only input field for convenience.
	// All keys and values are merged into the data field on write, overwriting any existing values.
	// The stringData field is never output when reading from the API.
	// +k8s:conversion-gen=false
	// +optional
	StringData map[string]string `json:"stringData,omitempty" protobuf:"bytes,4,rep,name=stringData"`
```

**Comment by travisghansen** [comment] 2021-04-29 13:43
Not entirely sure I understand how `stringData` relates to the issue but do you have the info needed to reproduce? Or something more that I can provide to help?

**Comment by isindir** [comment] 2021-04-29 14:19
> I think the RequeueAfter is not set on success (
> 
> https://github.com/isindir/sops-secrets-operator/blob/6f57f2eac972cfb00a0937c360985fc94cb80327/controllers/sopssecret_controller.go#L222
> 
> ) which is probably why the removal of unowned `Secret` wasn't picked up.

From @travisghansen message I read it as it was not successful reconciliation, as secret pre-existed - so it should have been re-triggered. Also I don't see why it should be triggered on success, as then everything is in sync and any CRUD on the owner and owning objects will trigger reconcile again.

> Please also note that `stringData` is not a separately persisted field in `Secret` resource.
I'm aware - specifically this field was chosen for convenience of editing `SopsSecrets` via `sops` command, I think mistake was to call it `data` instead of `stringSata`.

> Not entirely sure I understand how stringData relates to the issue
There were 2 changes in one PR - mapping `SopsSecret:Secret` `data to stringData` and `binaryData to data`, as well as behavioural change of the reconciliation loop (please correct me if I'm wrong @eplightning ). I don't have anything against 1st change, but second I think broke operator rather then fixed it. @travisghansen could you please re-test latest chart and confirm it works for you. 

I need to create tests in the code, which I don't have atm to avoid issues like this.

**Comment by travisghansen** [comment] 2021-04-29 14:30
Yeah, I'll re-test with the latest code for sure. Should I be renaming the `data` field then? Your explanation above probably explains why when I initially tested it was double base64 encoded so I agree that `stringData` makes more sense. I would mimic exactly the behavior of the upstream secret in that regards.

**Comment by isindir** [comment] 2021-04-29 14:36
@travisghansen only `data` should be used in `SopsSecret` for now...

**Comment by travisghansen** [comment] 2021-05-10 21:14
I was out most of last week, it's on my list to look at this week actually and report back.

**Comment by isindir** [comment] 2021-05-11 08:38
sorry, re-opening again

**Comment by travisghansen** [comment] 2021-05-14 21:56
Will look at this shortly.

**Comment by travisghansen** [comment] 2021-05-15 15:30
OK, so I've tried this again. I'm not sure what the normal reconciliation loop time is, but I've waited over 15 minutes and the thing seems to have stopped reconciling altogether.

```
{"level":"info","ts":1621090116.5949886,"logger":"controllers.SopsSecret","msg":"Reconciling","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621090116.6209545,"logger":"controllers.SopsSecret","msg":"Entering template data loop","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621090116.621162,"logger":"controllers.SopsSecret","msg":"Processing","sopssecret":"SopsSecret.isindir.github.com/v1alpha2.test-secret","type":"Opaque","namespace":"jfrog-platform","templateItem":"secret/test-secret"}
{"level":"info","ts":1621090116.6375463,"logger":"controllers.SopsSecret","msg":"Child secret is not owned by controller or sopssecret Error","sopssecret":"jfrog-platform/test-secret","error":"sopssecret has a conflict with existing kubernetes secret resource, potential reasons: target secret already pre-existed or is managed by multiple sops secrets"}
{"level":"info","ts":1621090116.6382632,"logger":"controllers.SopsSecret","msg":"Reconciling","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621090116.6421335,"logger":"controllers.SopsSecret","msg":"Entering template data loop","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621090116.6422088,"logger":"controllers.SopsSecret","msg":"Processing","sopssecret":"SopsSecret.isindir.github.com/v1alpha2.test-secret","type":"Opaque","namespace":"jfrog-platform","templateItem":"secret/test-secret"}
{"level":"info","ts":1621090116.6494403,"logger":"controllers.SopsSecret","msg":"Child secret is not owned by controller or sopssecret Error","sopssecret":"jfrog-platform/test-secret","error":"sopssecret has a conflict with existing kubernetes secret resource, potential reasons: target secret already pre-existed or is managed by multiple sops secrets"}
```

I've deleted the `secret` *after* the above messages and it just appears to be doing nothing now (not even seeing log messages about reconciling all the other secrets). Is it stuck in a loop?

**Comment by isindir** [comment] 2021-05-15 15:48
This looks like a configuration error, lets go through the example:

```
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: example-sopssecret
spec:
  secretTemplates:
    - name: jenkins-secret
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
      annotations:
        "jenkins.io/credentials-description" : "credentials from Kubernetes"
      data:
        username: myUsername
        password: 'Pa$$word'
    - name: some-token
      data:
        token: Wb4ziZdELkdUf6m6KtNd7iRjjQRvSeJno5meH4NAGHFmpqJyEsekZ2WjX232s4Gj
    - name: docker-login
      type: 'kubernetes.io/dockerconfigjson'
      data:
        .dockerconfigjson: '{"auths":{"index.docker.io":{"username":"imyuser","password":"mypass","email":"myuser@abc.com","auth":"aW15dXNlcjpteXBhc3M="}}}'
```

When `example-sopssecret` of type `SopsSecret` like above is applied, operator tries to decrypt the content (above example is not encypted), and then tries to create resources of type `Secret` with names: `jenkins-secret`, `some-token`, `docker-login`. If any of these `Secrets` already exists in the namespace and is not set to be owned by same `SopsSecret` your are supposed to see an error which you mentioned. That means that the target secret can't be created or updated.

Try to create completely fresh namespace, create `SopsSecret` in there, choose unique names for items in `secretTemplates`. These names must not clash with existing k8s secret names.

The operator will try to reconcile preiodically `SopsSecret` object if there were any problems like mentioned above.

Then if everything has reconciled without issues - it should react on changes to both `SopsSecret` and `Secret` objects.

**Comment by isindir** [comment] 2021-05-15 15:51
I'd be happy to help diagnose the issue via "zoom" session, the best way is to ping me on Keybase.io . I have account with the same id as in github there.

**Comment by travisghansen** [comment] 2021-05-15 15:57
Actually this just came through..

Old pod

```
E0515 15:52:50.089617       1 leaderelection.go:321] error retrieving resource lock operators/ca57d051.github.com: context deadline exceeded
I0515 15:52:50.583131       1 leaderelection.go:278] failed to renew lease operators/ca57d051.github.com: timed out waiting for the condition
{"level":"info","ts":1621093970.659183,"logger":"controller-runtime.manager.controller.sopssecret","msg":"Stopping workers","reconciler group":"isindir.github.com","reconciler kind":"SopsSecret"}
{"level":"error","ts":1621093970.6403964,"logger":"setup","msg":"problem running manager","error":"leader election lost","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nmain.main\n\t/workspace/main.go:106\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

New pod

```
...
{"level":"info","ts":1621094012.9386392,"logger":"controllers.SopsSecret","msg":"Reconciling","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621094012.9405158,"logger":"controllers.SopsSecret","msg":"Entering template data loop","sopssecret":"jfrog-platform/test-secret"}
{"level":"info","ts":1621094012.9406972,"logger":"controllers.SopsSecret","msg":"Processing","sopssecret":"SopsSecret.isindir.github.com/v1alpha2.test-secret","type":"Opaque","namespace":"jfrog-platform","templateItem":"secret/test-secret"}
{"level":"info","ts":1621094012.9408157,"logger":"controllers.SopsSecret","msg":"Creating a new Secret","sopssecret":"jfrog-platform/test-secret","message":"Secret \"test-secret\" not found"}
{"level":"info","ts":1621094012.947614,"logger":"controllers.SopsSecret","msg":"Secret already exists and needs to be refreshed","secret":"test-secret","namespace":"jfrog-platform"}
{"level":"info","ts":1621094012.9529736,"logger":"controllers.SopsSecret","msg":"Secret successfully refreshed","secret":"test-secret","namespace":"jfrog-platform"}
{"level":"info","ts":1621094012.960153,"logger":"controllers.SopsSecret","msg":"SopsSecret is Healthy","sopssecret":"jfrog-platform/test-secret"}
...
```

**Comment by travisghansen** [comment] 2021-05-15 16:00
Note, I made no changes to the resources so I'm properly configuring the `sopsecret` (I'm using several others as well). It's just this particular workflow is causing the operator to get into a bad state it appears.

**Comment by travisghansen** [comment] 2021-05-15 16:04
Also note, I'm *intentionally* testing the situation where the `secret` already exists. I do expect the `sopssecret` to complain initially, but *after* I manually delete the existing `secret` I would expect the `sopssecret` to eventually notice that there is no longer a collision and properly (re)create the target `secret`.

**Comment by isindir** [comment] 2021-05-15 17:16
So if you are deleting pod, the operator restarts and recreates the secret correctly, but not recreating the secret in case when it has not been restarted ?

**Comment by travisghansen** [comment] 2021-05-15 19:03
Yeah, but for context only when a `sopssecret` is created where the associated `secret` already exists. If the `secret` does not exist then everything seems to be fine.

And also to be clear, *I* didn't delete the pod, it crashed presumably due to the above errors and then the deployment restarted it. From what I can tell it appears the code is hitting some sort of loop that it doesn't get out of when those specific steps are taken.

**Comment by isindir** [comment] 2021-05-16 10:57
@travisghansen , thanks for reposrting and helping.

Following changes:
https://github.com/isindir/sops-secrets-operator/pull/70/files#diff-67f21185a11c234dac59fe4d2e98aee91f765b84760cbb92055895e294fe1ed0R179

and

https://github.com/isindir/sops-secrets-operator/pull/70/files#diff-bec4c65fc95a35d847cabde53e79a7c2c6f2c327d577e399c0bdacb8fc8dab28R14

Should fix both of the issues you've raised.

**Comment by travisghansen** [comment] 2021-05-16 13:14
Awesome let me try it out! Just so I’m clear is the fix in the image deployed by 0.8.2?

**Comment by isindir** [comment] 2021-05-16 13:26
It will be, but at the moment I have trouble running it through CicrcleCI pipeline, it fails to pull go dependencies for some reason.

I've tested described behaviour locally with kind cluster:
* kind create cluster
* make docker-build
* kind load docker-image
* install CRD and helm chart, so that it does not pull image from dockerhub

I'm using age for local testing encrypt/decrypt .

btw, Thank you for `democratic-csi`, I'm using it on RPI cluster with TrueNas .

**Comment by travisghansen** [comment] 2021-05-16 13:38
Awesome! Didn't realize you used `democratic-csi`! This is a great operator as well, I'm excited to roll it out. I guess just ping when the images get finished as the clusters I run this in would be difficult to install images on. I'll get everything else prepped in the meantime to push the deploy button and do the test again.

**Comment by isindir** [comment] 2021-05-16 14:58
@travisghansen I finally merged it and released. Latest helm chart should point to the latest image:

Image: 0.2.1
Chart: 0.8.2

**Comment by travisghansen** [comment] 2021-05-16 22:07
This looks better thanks! The only thing on the wishlist at this point related to this bug would be possibly to add a `watch` on the existing `secret` to make it reconcile immediately in such scenarios vs waiting for the reconcile loop.

Seems resolved though!

**Comment by isindir** [comment] 2021-05-19 21:10
Thanks for testing, closing issue.

**Closed by isindir** 2021-05-19 21:10 UTC
Labels: bug
